# Generated by Django 3.1 on 2021-05-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_document_downloadlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='downloadlink',
            field=models.URLField(default=''),
        ),
    ]
