# Generated by Django 3.1 on 2021-05-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210507_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='downloadlink',
            field=models.URLField(default='', editable=False),
        ),
    ]
