# Generated by Django 3.1 on 2021-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='content',
            field=models.TextField(default='something.png'),
            preserve_default=False,
        ),
    ]
