# Generated by Django 3.1 on 2021-05-12 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_crop_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('doc_order', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.space')),
            ],
            options={
                'ordering': ['space', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.agentgroup')),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentUpdate',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.agent')),
                ('urltoken', models.CharField(max_length=100, unique=True)),
                ('token_confirm', models.BooleanField(default=False)),
                ('content_confirm', models.BooleanField(default=False)),
                ('contentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.document')),
            ],
        ),
    ]
