# Generated by Django 3.1 on 2021-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210514_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='viewcount',
        ),
        migrations.AddField(
            model_name='crop',
            name='agentid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
