# Generated by Django 3.1 on 2021-05-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210515_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='interactiontime',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='cropfile',
            field=models.FileField(blank=True, upload_to='crops'),
        ),
    ]
