# Generated by Django 3.1 on 2021-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210515_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='interactiontime',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
