# Generated by Django 3.1 on 2021-06-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210515_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['docfile']},
        ),
    ]
