# Generated by Django 3.1 on 2021-06-01 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210601_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentprogram',
            name='doc_order',
        ),
        migrations.AlterField(
            model_name='agentgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProgramEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=10)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.document')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.contentprogram')),
            ],
        ),
    ]
