# Generated by Django 3.1 on 2021-06-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210601_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentupdate',
            name='urltoken',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
