# Generated by Django 3.1 on 2021-06-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210601_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['group', 'id', 'name']},
        ),
    ]
