# Generated by Django 3.1 on 2021-06-01 22:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_person_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='descriptor',
            field=jsonfield.fields.JSONField(default=0),
            preserve_default=False,
        ),
    ]
