# Generated by Django 3.1 on 2021-06-07 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_document_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprogram',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
