# Generated by Django 3.1 on 2021-06-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20210607_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='agentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agent'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.document'),
        ),
    ]
