# Generated by Django 3.1 on 2021-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20210608_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='anger',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='attention',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='contempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='disgust',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='fear',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='frames',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='happiness',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='neutral',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='sadness',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='surprise',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
