# Generated by Django 3.1 on 2021-06-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20210611_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentupdate',
            name='token_confirm',
        ),
        migrations.RemoveField(
            model_name='agentupdate',
            name='urltoken',
        ),
        migrations.AddField(
            model_name='agentupdate',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agentupdate',
            name='expires_max',
            field=models.DateTimeField(null=True),
        ),
    ]
