# Generated by Django 3.1 on 2021-06-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20210613_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentupdate',
            name='url_hash',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
