# Generated by Django 3.2.5 on 2021-07-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20210724_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
