# Generated by Django 3.2.5 on 2021-08-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
