# Generated by Django 3.2.8 on 2021-10-08 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20211008_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parentdir',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.folder'),
            preserve_default=False,
        ),
    ]
