# Generated by Django 3.2.8 on 2021-10-08 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_folder_parentdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytlink',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
