# Generated by Django 3.2.8 on 2021-10-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_ytlink_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parentdir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.folder'),
        ),
    ]
