# Generated by Django 3.2.8 on 2021-10-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_folder_parentdir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ytlink',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='ytlink',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
