# Generated by Django 3.2.8 on 2021-10-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20211008_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created',
            new_name='added',
        ),
    ]
