# Generated by Django 3.2.8 on 2021-10-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0045_rename_created_document_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dashboard.document_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ytlink',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dashboard.ytlink_set+', to='contenttypes.contenttype'),
        ),
    ]
