# Generated by Django 3.2.8 on 2021-10-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0046_auto_20211016_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentupdate',
            name='content',
        ),
        migrations.RemoveField(
            model_name='agentupdate',
            name='contentid',
        ),
        migrations.RemoveField(
            model_name='document',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ytlink',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='agentupdate',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='agentupdate',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stats',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
