# Generated by Django 3.2.8 on 2021-10-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20211018_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentupdate',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='agentupdate',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='object_id',
        ),
        migrations.AddField(
            model_name='agentupdate',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.document'),
        ),
        migrations.AddField(
            model_name='agentupdate',
            name='contentid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stats',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.document'),
        ),
    ]
