# Generated by Django 3.2.8 on 2021-10-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20211018_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentupdate',
            name='contentid',
        ),
        migrations.AddField(
            model_name='agentupdate',
            name='ytcontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ytlink'),
        ),
    ]
