# Generated by Django 3.2.8 on 2021-10-18 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20211018_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programentry',
            name='doc',
        ),
        migrations.AddField(
            model_name='crop',
            name='ytcontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ytlink'),
        ),
        migrations.AddField(
            model_name='programentry',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.document'),
        ),
        migrations.AddField(
            model_name='programentry',
            name='ytcontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ytlink'),
        ),
        migrations.AddField(
            model_name='stats',
            name='ytcontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ytlink'),
        ),
        migrations.AddField(
            model_name='ytlink',
            name='viewtime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crop',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.document'),
        ),
    ]
