# Generated by Django 3.2.8 on 2021-10-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_ytlink_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytlink',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
