# Generated by Django 3.2.8 on 2021-12-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20211028_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentupdate',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='update', serialize=False, to='dashboard.agent'),
        ),
    ]
